## Import Libraries¶

In [1]:
## for loading and preprocessing 
import pandas as pd
import numpy as np

In [2]:
## read dataset
data = pd.read_csv("datasets/Housing.csv")

In [3]:
## create a deep copy 
df = data.copy()

## Data Preview And Understanding

- Loading the dataset

In [4]:
## view the first rows 
df.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished

In [5]:
## view the last five rows 
df.tail()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
540  1820000  3000         2          1        1      yes        no      yes   
541  1767150  2400         3          1        1       no        no       no   
542  1750000  3620         2          1        1      yes        no       no   
543  1750000  2910         3          1        1       no        no       no   
544  1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished

In [6]:
## checking data
df

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

## Understanding Data

In [7]:
## total size of the datd
len(df)

545

In [8]:
## maximum of the data
max(df)

'stories'

In [9]:
## minimum of the data
min(df)

'airconditioning'

In [10]:
## total max data
df.max()

price                  13300000
area                      16200
bedrooms                      6
bathrooms                     4
stories                       4
mainroad                    yes
guestroom                   yes
basement                    yes
hotwaterheating             yes
airconditioning             yes
parking                       3
prefarea                    yes
furnishingstatus    unfurnished
dtype: object

In [11]:
## total min data
df.min()

price                 1750000
area                     1650
bedrooms                    1
bathrooms                   1
stories                     1
mainroad                   no
guestroom                  no
basement                   no
hotwaterheating            no
airconditioning            no
parking                     0
prefarea                   no
furnishingstatus    furnished
dtype: object

In [12]:
## total rows and columns
df.shape

(545, 13)

In [13]:
## total memory allocation
df.size

7085

In [14]:
## knowing about the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   price             545 non-null    int64 
 1   area              545 non-null    int64 
 2   bedrooms          545 non-null    int64 
 3   bathrooms         545 non-null    int64 
 4   stories           545 non-null    int64 
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64 
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB


In [15]:
## checking for missing values
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [16]:
## checking for duplicated values 
df.duplicated().sum()

0

In [17]:
## checking type on columns
df.dtypes

price                int64
area                 int64
bedrooms             int64
bathrooms            int64
stories              int64
mainroad            object
guestroom           object
basement            object
hotwaterheating     object
airconditioning     object
parking              int64
prefarea            object
furnishingstatus    object
dtype: object

## Finding unique instances in each column

In [18]:
print(np.unique(df['price']))

[ 1750000  1767150  1820000  1855000  1890000  1960000  2100000  2135000
  2233000  2240000  2275000  2310000  2345000  2380000  2408000  2450000
  2485000  2520000  2590000  2604000  2653000  2660000  2695000  2730000
  2800000  2835000  2852500  2870000  2940000  2961000  2975000  3003000
  3010000  3045000  3080000  3087000  3115000  3118850  3129000  3143000
  3150000  3220000  3234000  3255000  3290000  3325000  3332000  3353000
  3360000  3395000  3423000  3430000  3465000  3493000  3500000  3535000
  3570000  3605000  3633000  3640000  3675000  3703000  3710000  3745000
  3773000  3780000  3815000  3836000  3850000  3885000  3920000  3990000
  4007500  4025000  4060000  4095000  4098500  4123000  4130000  4165000
  4193000  4200000  4235000  4270000  4277000  4305000  4319000  4340000
  4375000  4382000  4403000  4410000  4445000  4473000  4480000  4515000
  4543000  4550000  4585000  4613000  4620000  4655000  4690000  4753000
  4760000  4767000  4795000  4830000  4865000  4893

In [19]:
print(np.unique(df['area']))

[ 1650  1700  1836  1905  1950  2000  2015  2135  2145  2160  2175  2176
  2275  2325  2398  2400  2430  2475  2500  2520  2550  2610  2640  2650
  2684  2700  2747  2787  2800  2817  2835  2850  2856  2870  2880  2910
  2953  2970  2990  3000  3036  3040  3060  3069  3090  3100  3120  3150
  3162  3180  3185  3210  3240  3264  3290  3300  3350  3360  3400  3410
  3420  3450  3460  3480  3500  3510  3512  3520  3540  3570  3584  3600
  3620  3630  3635  3640  3649  3650  3660  3680  3700  3720  3745  3750
  3760  3780  3792  3800  3816  3840  3850  3880  3900  3930  3934  3960
  3968  3970  3986  3990  4000  4032  4040  4046  4050  4075  4079  4080
  4095  4100  4120  4130  4160  4200  4240  4260  4280  4300  4320  4340
  4350  4352  4360  4370  4400  4410  4500  4510  4520  4560  4600  4632
  4640  4646  4700  4750  4770  4775  4785  4800  4815  4820  4840  4880
  4900  4920  4950  4960  4990  4992  4995  5000  5010  5020  5040  5076
  5136  5150  5170  5200  5300  5320  5360  5400  5

In [20]:
print(np.unique(df['bedrooms']))

[1 2 3 4 5 6]


In [21]:
print(np.unique(df['bathrooms']))

[1 2 3 4]


In [22]:
print(np.unique(df['stories']))

[1 2 3 4]


In [23]:
print(np.unique(df['mainroad']))

['no' 'yes']


In [24]:
print(np.unique(df['guestroom']))

['no' 'yes']


In [25]:
print(np.unique(df['basement']))

['no' 'yes']


In [26]:
print(np.unique(df['hotwaterheating']))

['no' 'yes']


In [27]:
print(np.unique(df['airconditioning']))

['no' 'yes']


In [28]:
print(np.unique(df['parking']))

[0 1 2 3]


In [29]:
print(np.unique(df['prefarea']))

['no' 'yes']


In [30]:
print(np.unique(df['furnishingstatus']))

['furnished' 'semi-furnished' 'unfurnished']


## Checking each colums

In [31]:
df['price']

0      13300000
1      12250000
2      12250000
3      12215000
4      11410000
         ...   
540     1820000
541     1767150
542     1750000
543     1750000
544     1750000
Name: price, Length: 545, dtype: int64

In [32]:
df['area']

0      7420
1      8960
2      9960
3      7500
4      7420
       ... 
540    3000
541    2400
542    3620
543    2910
544    3850
Name: area, Length: 545, dtype: int64

In [33]:
df['bedrooms']

0      4
1      4
2      3
3      4
4      4
      ..
540    2
541    3
542    2
543    3
544    3
Name: bedrooms, Length: 545, dtype: int64

In [34]:
df['bathrooms']

0      2
1      4
2      2
3      2
4      1
      ..
540    1
541    1
542    1
543    1
544    1
Name: bathrooms, Length: 545, dtype: int64

In [35]:
df['stories']

0      3
1      4
2      2
3      2
4      2
      ..
540    1
541    1
542    1
543    1
544    2
Name: stories, Length: 545, dtype: int64

In [36]:
df['mainroad']

0      yes
1      yes
2      yes
3      yes
4      yes
      ... 
540    yes
541     no
542    yes
543     no
544    yes
Name: mainroad, Length: 545, dtype: object

In [37]:
df['guestroom']

0       no
1       no
2       no
3       no
4      yes
      ... 
540     no
541     no
542     no
543     no
544     no
Name: guestroom, Length: 545, dtype: object

In [38]:
df['basement']

0       no
1       no
2      yes
3      yes
4      yes
      ... 
540    yes
541     no
542     no
543     no
544     no
Name: basement, Length: 545, dtype: object

In [39]:
df['hotwaterheating']

0      no
1      no
2      no
3      no
4      no
       ..
540    no
541    no
542    no
543    no
544    no
Name: hotwaterheating, Length: 545, dtype: object

In [40]:
df['airconditioning']

0      yes
1      yes
2       no
3      yes
4      yes
      ... 
540     no
541     no
542     no
543     no
544     no
Name: airconditioning, Length: 545, dtype: object

In [41]:
df['parking']

0      2
1      3
2      2
3      3
4      2
      ..
540    2
541    0
542    0
543    0
544    0
Name: parking, Length: 545, dtype: int64

In [42]:
df['prefarea']

0      yes
1       no
2      yes
3      yes
4       no
      ... 
540     no
541     no
542     no
543     no
544     no
Name: prefarea, Length: 545, dtype: object

In [43]:
df['furnishingstatus']

0           furnished
1           furnished
2      semi-furnished
3           furnished
4           furnished
            ...      
540       unfurnished
541    semi-furnished
542       unfurnished
543         furnished
544       unfurnished
Name: furnishingstatus, Length: 545, dtype: object

## Data preprocessing
- Normalizing column names

In [44]:
## Getting a brief statistical summary of the dataframe
df.describe().round()

price     area  bedrooms  bathrooms  stories  parking
count       545.0    545.0     545.0      545.0    545.0    545.0
mean    4766729.0   5151.0       3.0        1.0      2.0      1.0
std     1870440.0   2170.0       1.0        1.0      1.0      1.0
min     1750000.0   1650.0       1.0        1.0      1.0      0.0
25%     3430000.0   3600.0       2.0        1.0      1.0      0.0
50%     4340000.0   4600.0       3.0        1.0      2.0      0.0
75%     5740000.0   6360.0       3.0        2.0      2.0      1.0
max    13300000.0  16200.0       6.0        4.0      4.0      3.0

In [45]:
df. columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')

In [46]:
df.rename(columns={"price": "Price", "area": "Area" , "bedrooms": "Bed-rooms", "bathrooms": "Bath-rooms" }, inplace=True)

In [47]:
df.rename(columns={"stories": "Stories", "mainroad": "Main-road" , "guestroom": "Guest-room", "basement": "Basement" }, inplace=True)

In [48]:
df.rename(columns={"hotwaterheating": "Hot-water-heating", "airconditioning": "Air-conditioning"}, inplace=True)

In [49]:
df.rename(columns={"parking": "Parking", "prefarea": "Preffered-area" , "furnishingstatus": "Furnishing-status" }, inplace=True)

In [50]:
df. columns

Index(['Price', 'Area', 'Bed-rooms', 'Bath-rooms', 'Stories', 'Main-road',
       'Guest-room', 'Basement', 'Hot-water-heating', 'Air-conditioning',
       'Parking', 'Preffered-area', 'Furnishing-status'],
      dtype='object')

In [54]:
df. columns

Index(['Price', 'Area', 'Bed-rooms', 'Bath-rooms', 'Stories', 'Main-road',
       'Guest-room', 'Basement', 'Hot-water-heating', 'Air-conditioning',
       'Parking', 'Preffered-area', 'Furnishing-status'],
      dtype='object')